const START_NUMBER_ARRAY = 0;
const DOUBLE_REPEAT = 2;
const TOP_RATED = 'Top rated';
const MOST_COMMENTED = 'Most commented';
const FILMS_COUNT = 20;
const COMMENTS_COUNT = 20;
const N_REPEAT = 5;
const POPUP_MODE = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

export {
  DOUBLE_REPEAT, START_NUMBER_ARRAY,
  TOP_RATED, MOST_COMMENTED, FILMS_COUNT, COMMENTS_COUNT, N_REPEAT, POPUP_MODE
};
